### ISSUE TITLE
hashtag detection matches unintended markup

### ISSUE THREAD

**Issue by bdeshi** [pfefferle/wordpress-activitypub#129]
hi, this is a both a bug report and feature request. 

## The Bug

the Hashtag detection option can match unintended markup.<br>
I was creating a mermaid flowchart with the [Visualize](https://wordpress.org/plugins/visualize/) plugin, which generates svg from mermaid chart syntax. This svg element can contain <style> tags within.<br>
ActivityPub captured some parts of the markup (like css id and hex color definitions) and converted them to tags.

Not all hash-prefixed strings got converted though. I've collected [a fragment of the correct html/svg](https://gist.github.com/bdeshi/cc77210bc061c941eb79eaaeec2f5715#file-original-fragment-html) rendering, and the changes activitypub made after enabling hashtag detection as [a patch over the fragment text](https://gist.github.com/bdeshi/cc77210bc061c941eb79eaaeec2f5715#file-hashtag-on-patch).

#### Steps to reproduce:

1. spin up a fresh wp instance (I tried on wpsandbox.org)
2. install the plugins [Visualize](https://wordpress.org/plugins/visualize/) and  [Activitypub](https://wordpress.org/plugins/activitypub/)
3. Create a new post with the block editor.
4. Add a mermaidjs block with the content below:
    ````
    pie
      title pizza
        "pizza": 1
        "not pizza": 0
    ````
5. publish and open the post.

**Result**:
- chart rendering is broken.
- a bunch of unintended tags are generated.

## the Request

I haven't really dug into the code here. Is it possible to limit where hashtags are checked? maybe as blacklist/whitelist of regex patterns or html tag list? If not, can this be implemented as part of user configuration?

**Comment by redmatrix** [comment]
Wanted to note that we've dealt with similar problems in some other activitypub implementations by identifying problematic HTML tags ('code' is another) and escaping them by turning their tag content into base64 with a special prefix before handing off to the tag replacement function. Then we restore that immediately afterward by identifying the special prefixes in the body and base64 decoding them. 

Be advised that there's a very low and possibly zero chance of these svg's federating. My own projects allow inline svg but heavily purify it, as it's a great malware attack vector. So the entire style is going to be purified away when we receive it. The one in your gist will probably not survive purification and still be recognisable because stroke and fill are all in css. Based on tests I did a year or two ago, every other fediverse platform will purify the entire svg away. You might be able to work around this by converting to a file attachment, but it would need to be stored someplace where it can be fetched remotely. So this would be a real file. I have already tried data: urls and didn't have much luck federating them either, but admittedly I only tried this on Mastodon and Pleroma. A few projects *might* permit these.
