### ISSUE TITLE
Cannot follow user with email address as name

### ISSUE THREAD

**Issue by Downes** [pfefferle/wordpress-activitypub#152]
In a WordPress environment with ActivityPub installed, I can successfully follow @Downes@leftish.media from Mastodon, but cannot follow @stephen@downes.ca@leftish.media

The problem may be related to the behaviour of the Web Finger plugin, as 'Downes' resolves nicely: https://leftish.media/.well-known/webfinger?resource=acct:Downes@leftish.media 
while 'stephen@downes.ca' does not: https://leftish.media/.well-known/webfinger?resource=acct:stephen@downes.ca@leftish.media

The error appears to be caused by the parsing of username and website URL from the identifier. It appears to be splitting at the first '@' which would result in a username of 'stephen' and a website of 'downes.ca@leftish.media' whereas it should be split at the last '@', which would result in a username of 'stephen@downes.ca' and 'leftish.media'.

This issue may exist in several plugins. It may also exist in ActivityPub clients as well, such as Mastodon.

**Comment by mediaformat** [comment]
Interesting edge case

While the [spec](https://datatracker.ietf.org/doc/html/rfc7565#section-4) is meant to support this: 

> A common scenario is for a user to register with a service provider
   using an identifier (such as an email address) that is associated
   with some other service provider.  For example, a user with the email
   address "juliet@capulet.example" might register with a commerce
   website whose domain name is "shoppingsite.example".  In order to use
   her email address as the localpart of the 'acct' URI, the at-sign
   character (U+0040) needs to be percent-encoded as described in
   [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)].  Thus, the resulting 'acct' URI would be
   "acct:juliet%40capulet.example@shoppingsite.example".

Even [webfinger.net](https://webfinger.net/lookup/?resource=stephen%40downes.ca%40leftish.media), which seems to be the reference implementation tries to fetch the resource from https://downes.ca%40leftish.media

> 15:48:11 Looking up WebFinger data for acct:stephen@downes.ca@leftish.media
15:48:11 GET https://downes.ca%40leftish.media/.well-known/webfinger?resource=acct%3Astephen%40downes.ca%40leftish.media
15:48:11 Error getting JRD: parse https://downes.ca%40leftish.media/.well-known/webfinger?resource=acct%3Astephen%40downes.ca%40leftish.media: invalid URL escape "%40"

I've opened a ticket there to start: https://github.com/webfinger/webfinger.net/issues/28
