### ISSUE TITLE
question: .well-known folder

### ISSUE THREAD

**Issue by marc0janssen** [pfefferle/wordpress-activitypub#207]
Hi,

I checked via FTP in the web-root of my Wordpress installation.
But no where there is a .well-known folder to be found.

Am I doing something wrong?
Has my Hoster stripped this?
Do I need to create this .well-known folder myself?

Can you please advice?

Best regards,
Marco

**Comment by pfefferle** [comment]
The plugin does not create a `.well-known` folder, this is a mod-rewrite link, like the "pretty permalinks". If it does not work, it might collide with the ssl configuration of some hosters (because it might also use the .well-known folder). Maybe this helps https://github.com/pfefferle/wordpress-activitypub/issues/188 ?

**Comment by marc0janssen** [comment]
In the meantime hosting my own Wordpress instance... all ok now...
