### ISSUE TITLE
Webfinger endpoint not found.

### ISSUE THREAD

**Issue by YuriGal** [pfefferle/wordpress-activitypub#295]
I can't make it work for my site https://codecorner.galanter.net. It expect webfinger endpoint https://codecorner.galanter.net/.well-known/webfinger?resource=acct:yuriy@codecorner.galanter.net to be there, but I am getting 404.

I am using Bitnami Wordpress installation with Letsencrypt installed. I think it's using `.well-known` for acme challenge. Is there way to keep this working as is, and add webfinger support?

Thanks!

**Comment by YuriGal** [comment]
So I did a bit of hackering, and the endpoint now returns required (I think) [response](https://codecorner.galanter.net/.well-known/webfinger?resource=acct:yuriy@codecorner.galanter.net). But still site health check tells me it's invalid, and I cannot find my WordPress user from Mastodon. I am still missing something...

**Comment by davmillar** [comment]
@YuriGal I am seeing a 404 response at the URL you mentioned. When I had a similar issue, I noted that the redirects and REST API pieces were not configured as expected because I was using WP Multisite and did a network activate. I was able to resolve by network deactivating and then individually activating it on each site where it was wanted. Perhaps you could try something similar? I tried reaching the handler without the redirect and it gave a similar result to what I saw before:
https://codecorner.galanter.net/index.php?rest_route=/activitypub/1.0/webfinger?resource=acct:yuriy@codecorner.galanter.net

`{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}`

**Comment by YuriGal** [comment]
So sorry, I haven't gotten the response in a while, so I deactivated the plugin. 
But I do run WP Multisite too! And I did do "network activate", will try now what you suggested.

**Comment by YuriGal** [comment]
Holy crap, it's working now. I added that Rewrite block to `/opt/bitnami/apps/letsencrypt/conf/httpd-app.conf`

```
<Directory "/opt/bitnami/apps/letsencrypt/.well-known">
    Options +MultiViews
    AllowOverride None
    <IfVersion < 2.3 >
        Order allow,deny
        Allow from all
    </IfVersion>
    <IfVersion >= 2.3>
        Require all granted
    </IfVersion>
	
    RewriteEngine On
    RewriteBase /.well-known/
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /index.php?well_known_path=$1 [QSA,L]
	
</Directory>
```

Site health still fails, but the blog is now found on Fediverse.

**Comment by Nullcaller** [comment]
I had the same issue with my setup. I have a 'main' server that handles all http/https requests for an IP address, and forwards requests to a WordPress instance on a 'secondary' server via the use of `ProxyPass` and `ProxyPassReverse`. The issue was, Certbot was hosted on the 'main' server, and Apache was configured not to proxy the `.well-known` directory, so that Certbot could do its job. It was solved by adding `PT` flag to the `RewriteRule` above:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^/.well-known/(.*)$ /index.php?well_known_path=$1 [QSA,L,PT]
```

This way, the result of the rewrite rule is passed back to the `ProxyPass` directives, and since it doesn't match the first `ProxyPass "/.well-known/" "!"` directive, it gets proxied successfully by the second one.
