### ISSUE TITLE
Private/public keys not generated

### ISSUE THREAD

**Issue by skotperez** [pfefferle/wordpress-activitypub#31]
i’ve installed the plugin and i can’t find my site (vb@voragine.net) on Mastodon.

I’ve checked vb@voragine.net in webfinger and it is fine: https://client.webfinger.net/lookup?resource=vb%40voragine.net

The end point (https://voragine.net/.well-known/webfinger) throws some error message: “Missing parameter (s): resource”.

Apparently, the problem is that private/public keys haven't been generated.

[SSL support enabled in my PHP config](https://voragine.net/img/2019/02/Screenshot_2019-02-21-phpinfo.png).

**Comment by skotperez** [comment]
Any news from this? Anything i can do to help?

**Comment by alexgleason** [comment]
We're experiencing the exact same issue here: https://webfinger.net/lookup/?resource=nina%40blog.ninapaley.com

I can tell the plugin is working and the URL config is correct, because this page returns a JSON response: https://blog.ninapaley.com/.well-known/webfinger?resource=acct%3Anina%40blog.ninapaley.com

It says "Missing parameter(s): resource"

I'm in the process of checking if openssl PHP-extension is installed.

**Comment by alexgleason** [comment]
We confirmed openssl is installed 

![IMG_20190907_130001](https://user-images.githubusercontent.com/3639540/64478589-dc5a6f00-d16f-11e9-9865-5af19fa36127.jpg)

Anything else we can check?

**Comment by pfefferle** [comment]
Do you both use a caching plugin that also caches the wp-json api?

**Comment by pfefferle** [comment]
@skotperez and @alexgleason what is the PHP/WordPress version you are using?

**Comment by alexgleason** [comment]
WordPress 5.2.3.

I'm looking through the installed plugins now and nothing seems insane. It has "Quick Cache" so I added the .well-known path to the ignore list and cleared it. No change.

Should I can send you an email with a lot more info about the server and all installed plugins?

In theory since the endpoint is reached and properly returning json I think an interference with a plugin doesn't make sense to me.

**Comment by alexgleason** [comment]
PHP 7.2.22. Sorry, I missed that question.

**Comment by pfefferle** [comment]
You have to also add wp-json to the ignore path

**Comment by alexgleason** [comment]
I have 2 wordpress sites running on DreamHost.

ActivityPub works on my test site (a fresh install) and doesn't work on the other (an old site running for several years).

On my test site I installed the same plugins of the old site. I could not reproduce the problem.

I also compared phpinfo. The configuration is identical. Same PHP version, same MySQL, same Apache, same extensions installed.

The error, "Missing parameter(s): resource", seems to imply that PHP cannot read the GET parameter even though it's being passed. I wonder if this is a rewrite issue or something to do with Apache configuration. I'm requesting FTP access to the server to take a closer look.

**Comment by alexgleason** [comment]
Even after deactivating the plugin, the `/.well-known/webfinger` path still loads in my browser. I think you may be right that this is a caching issue.

I discovered a drop-in plugin called "advanced-cache.php". Gonna try to disable it. I'll report back if that helps.

**Comment by alexgleason** [comment]
I think I discovered where the issue lies:

* [blog.ninapaley.com/wp-json/activitypub/1.0/webfinger](https://blog.ninapaley.com/wp-json/activitypub/1.0/webfinger?resource=acct%3Anina%40blog.ninapaley.com) :heavy_check_mark: working
* [blog.ninapaley.com/.well-known/webfinger](https://blog.ninapaley.com/.well-known/webfinger?resource=acct%3Anina%40blog.ninapaley.com) :x: broken

My first thought is that there's some issue with Apache trying to route `/.well-known`, but it does seem to be handled by wp-json...

I'm not quite sure where to go from here, but glad I narrowed it down. I'm beginning to understand how this wp-json thing works.

**Comment by alexgleason** [comment]
I got it! It was due to already having a `.well-known` directory in the root of the webserver. Deleting that fixed it.

**Comment by timnolte** [comment]
Be advised, if you are using a Let's Encrypt SSL certificate that directory is used by it. It will get recreated when your cert renews.

**Comment by alexgleason** [comment]
Yes, I'm a bit concerned DreamHost is going to automatically recreate it when the cert updates and it'll break this plugin. Trying to figure out a way around that.

**Comment by pfefferle** [comment]
OK, then it is a problem with the default rewrite rules, WordPress adds to the .htaccess. Can you try to add them explicitly? I will try to reproduce it.

**Comment by pfefferle** [comment]
This is weird 😳
