### ISSUE TITLE
Can't find my blog on Mastodon

### ISSUE THREAD

**Issue by forteller** [pfefferle/wordpress-activitypub#46]
Hi. Thanks for a fantastic plugin! 

At least it sounds fantastic :D but I can't seem to get it to work :(

I installed it more than I week ago and I've published a post since. Still, In my Mastodon instance (octodon.social) I've searched for both of the adresses the plugin says I can search for many times (@whatevs@blogg.forteller.net and https://blogg.forteller.net/author/admin/) and still nothing shows up. 

I guess this is unrelated, but I even get zero results when searching for the new post I've published, even though I have linked to it in a normal toot :/

Am I doing anything wrong, or is this a bug? Thanks!

**Comment by pfefferle** [comment]
WebFinger seems not configured correctly on your site: https://client.webfinger.net/lookup?resource=whatevs%40blogg.forteller.net

* Have you enabled "pretty permalinks"?
* Do you run your website on NGINX? https://github.com/pfefferle/wordpress-activitypub/issues/5
* Is there a .well-known folder in your webspace?

**Comment by forteller** [comment]
Thanks for the help!

> Have you enabled "pretty permalinks"?

My posts are on URL/Year/Title, that's a pretty permalink, right?

> Do you run your website on NGINX?

I don't know. I have it on Dreamhost. How can I know?

> Is there a .well-known folder in your webspace?

Yes.

Now I've also installed the WebFinger extension. Do I need that too for this to work?

**Comment by ngm** [comment]
> Now I've also installed the WebFinger extension. Do I need that too for this to work?

I don't think so, no.  I have the ActivityPub plugin installed and working and I don't have the WebFinger plugin installed.

> Do you run your website on NGINX?

According to [builtwith](https://builtwith.com/?https%3a%2f%2fblogg.forteller.net%2f), your site is running Apache.

> Is there a .well-known folder in your webspace?

Something seems to be wrong here, as if you access either:

https://blogg.forteller.net/.well-known/webfinger?resource=acct:admin@blogg.forteller.net
https://blogg.forteller.net/.well-known/webfinger?resource=acct:whatevs@blogg.forteller.net

You get an error 'missing "resource" parameter'.  What happens if you remove the WebFinger plugin and try those links?

(Side note: is your account name whatevs or admin?)

**Comment by ejheil** [comment]
Hey, just as a data point, I was about to post in this thread about how nothing worked, and read "is there a .well-known folder in your webspace?"  I checked and damn, there totally was, six months old.  It dated to my fooling around with Indieweb stuff months ago.  I deleted the .well-known folder and suddenly we were in business. 

People who are having trouble with this: check for the presence of a .well-known folder if you've been fooling around with indieweb stuff in the past!

**Comment by Boundarybreaker** [comment]
I'm having the same issue, and don't seem to have gotten a `.well-known` folder. What should I do to have it be created?

**Comment by pfefferle** [comment]
@Boundarybreaker nothing have to be generated... `.well-known/webfinger` is generated as a virtual folder using mod_rewrite. You can check if you have "pretty permalinks" enabled.

**Comment by Boundarybreaker** [comment]
ahhhh, ok.

**Comment by Boundarybreaker** [comment]
I tried turning on pretty permalinks, and that broke post publishing - got an error saying "Publishing failed. The response is not a valid JSON response". I'm gonna try and figure out what's causing that.

**Comment by pfefferle** [comment]
@Boundarybreaker can you check your `.htaccess` file? https://wordpress.org/support/topic/publishing-failed-error-message-the-response-is-not-a-valid-json-response-2/#post-12979390

**Comment by Boundarybreaker** [comment]
I'm using nginx...

**Comment by pfefferle** [comment]
@Boundarybreaker https://github.com/pfefferle/wordpress-activitypub/blob/master/README.md#what-if-you-are-running-your-blog-in-a-subdirectory

**Comment by Boundarybreaker** [comment]
Could have sworn it's already set to nginx root, but I'll triple-check.

**Comment by Boundarybreaker** [comment]
oh wait, you edited your post. Lemme take a look.

**Comment by Boundarybreaker** [comment]
...alright, did the nginx config, and I just found out that wordpress is 404'ing my author page.

**Comment by pfefferle** [comment]
have you checked your pretty permalinks for posts? perhaps a misconfiguration?

**Comment by Boundarybreaker** [comment]
...huh, they 404 too. Looks like a misconfig. I'm gonna sleep now and fix this later.

**Comment by Boundarybreaker** [comment]
oh, it looks like I got the nginx config fixed for that, but it still doesn't seem to be working. I'll try and take another look tomorrow.

**Comment by rebelcode-xr** [comment]
I found another potential configuration issue:
![image](https://user-images.githubusercontent.com/63522951/147113669-23190ac2-02bc-49d6-9907-e8fc2b960518.png)
in Plesk I had to choose my favourite domain without "www", otherwise the federation would not work.

this problem might be avoided "plugin side" somehow, what do you think @pfefferle?

**Comment by pfefferle** [comment]
the plugin should work with and/or without `www.` or any other subdomain.

**Comment by rebelcode-xr** [comment]
testing with https://webfinger.net/ it seems that webfinger cannot find anymore the json if I put the 1st option...I've to look for test@www.domain.org instead of test@domain.org, otherwise doesn't work.
If I choose the 2nd (no www) or the 3rd (no favourite domain) option there's no issue.
probably the 1st option forces www and creates problems with webfinger, no idea.

anyway I just wanted to share this info in case somebody else has the same config: easy to solve! :)

**Comment by pfefferle** [comment]
@rebelcode-xr here is an example of a `www` Domain: https://webfinger.net/lookup/?resource=olaf%40www.bachgau.social

**Comment by pfefferle** [comment]
It is up to the domain configuration of WordPress, and that is what I use for AP. I can not force something else, because it might redirect or not work then.

**Comment by pfefferle** [comment]
Maybe a Pleak specific issue?

**Comment by rebelcode-xr** [comment]
> Maybe a Plesk specific issue?

Probably, so maybe nothing to worry about! :)
