### ISSUE TITLE
Post image shows twice on Mastodon

### ISSUE THREAD

**Issue by ldidry** [pfefferle/wordpress-activitypub#56]
Disclaimer: I talk about the images that are displayed before the posts, as a banner.

I don’t know if it’s a Mastodon bug that shows the image twice or if it’s the AP message that attachs the image twice.

If you look at my posts on Mastodon, the images shows twice (to look at my posts, put `@luc@fiat-tux.fr` in the search box and look at my stream — oddly, putting the URL of a post in it doesn’t work).

**Comment by timnolte** [comment]
I'm seeing some cases like this as well @timnolte@www.timnolte.com

**Comment by bekoli** [comment]
Same.
![image](https://user-images.githubusercontent.com/5016428/65322177-5c3bfc80-dba6-11e9-8ba4-98fe9b19a2dd.png)

Happens for Format `Standard` having _only_ `Featured Image` - no further inline image is used.

Switching the Activity-Object-Type between Note (default) and WordPress doesn't seen to have any effect on this.

The plugin `Mastodon Autopost` gets it right btw.

**Comment by bekoli** [comment]
Now this is weird. I added a Featured Image during draft. Previewed the post, didn't like it due to scale of this image and removed it again.

Post was later published and shows up over ActivityPub _with_ this removed Featured Image *that was never published* in the end.

Result instead of the usual two images when none was expected: One preview image.

![image](https://user-images.githubusercontent.com/5016428/65646153-6a50a980-dffa-11e9-8294-b99c75ab54fe.png)

The attached image is nowhere in the DOM when the post is rendered in the browser and also not found withing mf2. It's also not in the feed.
