### ISSUE TITLE
Support for Post Kinds

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-activitypub#67]
While I am not using ActivityPub right now, I have received word that Post Kinds doesn't play nicely with it in how the posts display. Opening this to discuss possible actions on one side or the other.

**Comment by pfefferle** [comment]
Do you have an example?

**Comment by bekoli** [comment]
Well if you use post-kinds that is e.g. "just" a Like without headline or text or excerpt added to it you will get "just" a link on some post. Looks like spam / bot and has no context whatsoever.

So to make this look nice one _has_ to add some own text and a headline.

![image](https://user-images.githubusercontent.com/5016428/65321817-817c3b00-dba5-11e9-8b2c-fe74674d63aa.png)

Compared to the page result:
![image](https://user-images.githubusercontent.com/5016428/65321865-a07acd00-dba5-11e9-901d-cbb25b4af69e.png)

And since there is no filter function all the quick actions usually issued via Micropub clutter the stream and make the account look like a broken bot.

**Comment by bekoli** [comment]
Duplicates #26

**Comment by pfefferle** [comment]
Close in favor of #26
