### ISSUE TITLE
Probably Problems with Space in Username

### ISSUE THREAD

**Issue by waweic** [pfefferle/wordpress-activitypub#71]
My Wordpress-Username has the following format: "My Username"
Thus, the generated Fediverse ID is "My Username@mydomain.tld", whereas the link to it is "https://mydomain.tld/author/my-username/".
My Problem is now that Mastodon won't follow this account and I suspect the space in the username to be the problem. Would it be possible to also user the "my-username"-part in the Fediverse ID? Or are there any other solutions? Am I wrong with my assumption that there may not be a space in the Fediverse ID?
Thanks for the great project, hope to hear from you soon

**Comment by skariko** [comment]
Hello! Same problem here, did you find how to fix it?

**Comment by mediaformat** [comment]
Technically you can search for a profile with a space in the username using [webfinger](https://webfinger.net/) and receive a valid response.
And you can fetch a profile using the links provided by webfinger.

The bug is with Mastodon, when pasting the author URL into Mastodon an error is returned:

> **Searching failed**
Server did not return an OK response code
(422: Validation failed: Username must contain only letters, numbers and underscores)

Searching Mastodon with webfinger seems to fail silently. Pleroma as well.

Zap finds the profile.

**Comment by skariko** [comment]
> 

Yeah I see: https://webfinger.net/lookup/?resource=marco+calamari%40www.lealternative.net

I think that a workaround will be create a new author without space and give it all the posts :)
